dataformCoreVersion: 3.0.8
defaultProject: winter-dataform
defaultLocation: us-central1
defaultDataset: tmdb
defaultAssertionDataset: tmdb_assertions
vars:
  LOAD_GCS_BUCKET: winter-data/tmdb
  STAGING_DATA: tmdb_staging
  TARGET_DATA: tmdb
